### ISSUE TITLE
基于gitalk实现hexo评论功能 | flynn-zhl的博客

### ISSUE THREAD

**Issue by flynna** [flynna/flynna.github.io#2]
https://flynna.github.io/2021/07/18/%E5%B7%A5%E5%85%B7%E6%96%87%E6%A1%A3/%E5%9F%BA%E4%BA%8Egitalk%E5%AE%9E%E7%8E%B0hexo%E8%AF%84%E8%AE%BA%E5%8A%9F%E8%83%BD/ 

 flynn-zhl的博客

**Comment by hlfly** [comment]
test comment

**Comment by hesiliao** [comment]
nice!
